# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJfwibU2r5Wv3bSe0HrRZgKpMmSNbSBl
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import math

GROUND_TRUTH = [
    # (input, symptom, sign, lag_days, strength)   sign: +1 aggravates, -1 relieves
    ("seed_oil", "joint_pain", +1, 2, 0.9),
    ("omega3",   "mood",       -1, 2, 0.8),   # mood scored so higher = worse here
    ("sugar",    "fatigue",    +1, 0, 1.2),
    ("turmeric", "joint_pain", -1, 4, 0.6),
]

DECOY_INPUTS = ["coffee", "pasta", "cheese", "banana", "salad", "soda", "bread", "eggs"]
SYMPTOMS = ["joint_pain", "mood", "fatigue", "cognitive_clarity", "sleep_quality"]

def generate_user(
    n_days: int = 120,
    missingness: float = 0.12,
    noise: float = 1.0,
    seed: int = 7,
    ) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    dates = pd.date_range("2025-01-01", periods=n_days, freq="D")

    inputs = {}
    real_inputs = [g[0] for g in GROUND_TRUTH]
    for name in real_inputs + DECOY_INPUTS:
        # Bursty intake: people eat foods in runs, not i.i.d.
        base = rng.random(n_days)
        smoothed = pd.Series(base).rolling(3, min_periods=1).mean().values
        inputs[name] = (smoothed * rng.uniform(0.8, 1.4)).round(2)
    X = pd.DataFrame(inputs, index=dates)

    stress = pd.Series(rng.normal(0, 1, n_days), index=dates) \
        .rolling(4, min_periods=1).mean()
    sleep_debt = pd.Series(rng.normal(0, 1, n_days), index=dates) \
        .rolling(3, min_periods=1).mean()

    symptoms = {}
    for s in SYMPTOMS:
        series = np.zeros(n_days)
        prev = rng.normal(5, 1.0)
        for t in range(n_days):
            # sticky autoregression — yesterday predicts today (moderate)
            val = 0.45 * prev + 0.55 * 5.0
            # confounders nudge several symptoms (a real, modest confound)
            val += 0.5 * stress.iloc[t]
            if s in ("fatigue", "cognitive_clarity", "sleep_quality"):
                val += 0.4 * sleep_debt.iloc[t]
            val += rng.normal(0, 0.9 * noise)
            series[t] = val
            prev = val
        symptoms[s] = series

    for inp, sym, sign, lag, strength in GROUND_TRUTH:
        x = X[inp].values
        for t in range(n_days):
            src = t - lag
            if src >= 0:
                symptoms[sym][t] += sign * 3.3 * strength * (x[src] - x.mean())

    Y = pd.DataFrame(symptoms, index=dates)
    # clip to a 0-10 clinical scale and round (mirrors a 0-10 symptom slider)
    Y = Y.apply(lambda c: np.clip(c, 0, 10)).round(0)

    df = pd.concat([X, Y, stress.rename("stress_load"),
                    sleep_debt.rename("sleep_debt")], axis=1)

    mask = rng.random((n_days, len(SYMPTOMS))) < missingness
    for j, s in enumerate(SYMPTOMS):
        df.loc[mask[:, j], s] = np.nan

    df.index.name = "date"
    return df

def input_columns():
    return [g[0] for g in GROUND_TRUTH] + DECOY_INPUTS


def truth_table():
    return pd.DataFrame(
        [{"input": i, "symptom": s,
          "direction": "aggravates" if sign > 0 else "relieves",
          "lag": lag} for i, s, sign, lag, _ in GROUND_TRUTH]
    )

import warnings
from dataclasses import dataclass, field, asdict
from typing import Optional

import numpy as np
import pandas as pd
from scipy import stats
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

@dataclass
class EngineConfig:
    min_lag_days: int = 0
    max_lag_days: int = 5

    min_paired_observations: int = 14

    min_effect_size: float = 0.20

    fdr_alpha: float = 0.10

    holdout_fraction: float = 0.30

    ridge_alpha: float = 1.0

    confounder_columns: tuple = ("stress_load", "sleep_debt", "dow_sin", "dow_cos")

    autoregressive_order: int = 2

@dataclass
class LaggedRelationship:
    input_name: str
    symptom_name: str
    best_lag_days: int
    effect_size: float          # partial correlation, signed
    direction: str              # "aggravates" | "relieves"
    p_value: float
    q_value: float              # FDR-adjusted
    n_observations: int
    distributed_lag_profile: dict = field(default_factory=dict)  # lag -> beta
    validated: Optional[bool] = None
    validation_detail: str = ""

    def human_summary(self) -> str:
        verb = "raises" if self.direction == "aggravates" else "lowers"
        lag = "same day" if self.best_lag_days == 0 else f"{self.best_lag_days}d later"
        conf = int((1 - self.q_value) * 100)
        return (f"{self.input_name} {verb} {self.symptom_name} ({lag}, "
                f"r={self.effect_size:+.2f}, ~{conf}% conf, n={self.n_observations})")


@dataclass
class Hypothesis:
    statement: str
    input_name: str
    symptom_name: str
    lag_days: int
    predicted_direction: str
    predicted_effect: float
    confidence: float
    based_on_relationship: LaggedRelationship


@dataclass
class HypothesisResult:
    hypothesis: Hypothesis
    confirmed: bool
    observed_effect: float
    observed_p: float
    verdict: str

class PersonalCorrelationEngine:

    def __init__(self, config: EngineConfig | None = None):
        self.cfg = config or EngineConfig()
        self.audit_trail: list[LaggedRelationship] = []

    def discover(
        self,
        df: pd.DataFrame,
        input_columns: list[str],
        symptom_columns: list[str],
    ) -> list[LaggedRelationship]:

        df = self._prepare_frame(df)

        # 1. Estimate every (input, symptom) distributed-lag relationship on the
        #    TRAIN portion only.
        split = int(len(df) * (1 - self.cfg.holdout_fraction))
        train, test = df.iloc[:split], df.iloc[split:]

        candidates: list[LaggedRelationship] = []
        for sym in symptom_columns:
            for inp in input_columns:
                rel = self._estimate_relationship(train, inp, sym)
                if rel is not None:
                    candidates.append(rel)

        self.audit_trail = candidates  # full record, including everything rejected
        if not candidates:
            return []

        candidates = self._apply_fdr(candidates)

        survivors = [
            c for c in candidates
            if c.q_value <= self.cfg.fdr_alpha
            and abs(c.effect_size) >= self.cfg.min_effect_size
        ]

        signals = []
        for rel in survivors:
            self._validate_out_of_sample(test, rel)
            if rel.validated:
                signals.append(rel)

        return sorted(signals, key=lambda r: r.q_value)

    def generate_hypothesis(
        self, relationships: list[LaggedRelationship]
    ) -> Optional[Hypothesis]:

        validated = [r for r in relationships if r.validated]
        if not validated:
            return None
        r = max(validated, key=lambda x: abs(x.effect_size))

        if r.direction == "aggravates":
            stmt = (f"Reducing {r.input_name} this week should LOWER your "
                    f"{r.symptom_name} at a ~{r.best_lag_days}-day lag.")
        else:
            stmt = (f"Increasing {r.input_name} this week should LOWER your "
                    f"{r.symptom_name} at a ~{r.best_lag_days}-day lag.")

        return Hypothesis(
            statement=stmt,
            input_name=r.input_name,
            symptom_name=r.symptom_name,
            lag_days=r.best_lag_days,
            predicted_direction=r.direction,
            predicted_effect=r.effect_size,
            confidence=1 - r.q_value,
            based_on_relationship=r,
        )

    def evaluate_hypothesis(
        self, hypothesis: Hypothesis, week_df: pd.DataFrame
    ) -> HypothesisResult:
        week_df = self._prepare_frame(week_df)
        x, y = self._lagged_pairs(
            week_df, hypothesis.input_name, hypothesis.symptom_name,
            hypothesis.lag_days,
        )
        if len(x) < 4:
            return HypothesisResult(
                hypothesis, confirmed=False, observed_effect=np.nan,
                observed_p=np.nan,
                verdict="Inconclusive — not enough data logged this week.",
            )
        r, p = stats.spearmanr(x, y)
        same_sign = (r > 0) == (hypothesis.predicted_direction == "aggravates")
        confirmed = bool(same_sign and p < 0.10)
        verdict = (
            f"Confirmed. {hypothesis.symptom_name} moved as predicted "
            f"(r={r:+.2f}, p={p:.2f})."
            if confirmed else
            f"Not confirmed this week (r={r:+.2f}, p={p:.2f}). The model will "
            f"down-weight this relationship."
        )
        return HypothesisResult(hypothesis, confirmed, float(r), float(p), verdict)


    def _prepare_frame(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        if not isinstance(df.index, pd.DatetimeIndex):
            if "date" in df.columns:
                df = df.set_index(pd.to_datetime(df["date"])).drop(columns=["date"])
            else:
                df.index = pd.to_datetime(df.index)
        df = df.sort_index()
        # Engineer cyclical day-of-week confounders (handles the "Tuesday" problem).
        dow = df.index.dayofweek
        df["dow_sin"] = np.sin(2 * np.pi * dow / 7)
        df["dow_cos"] = np.cos(2 * np.pi * dow / 7)
        return df

    def _build_confounders(self, frame: pd.DataFrame, symptom: str) -> pd.DataFrame:
        cols = {}
        for c in self.cfg.confounder_columns:
            if c in frame.columns:
                cols[c] = frame[c]
        # Autoregressive lags of the symptom itself.
        for k in range(1, self.cfg.autoregressive_order + 1):
            cols[f"{symptom}_ar{k}"] = frame[symptom].shift(k)
        return pd.DataFrame(cols, index=frame.index)

    def _estimate_relationship(
        self, frame: pd.DataFrame, inp: str, sym: str
    ) -> Optional[LaggedRelationship]:
        lags = list(range(self.cfg.min_lag_days, self.cfg.max_lag_days + 1))

        per_lag = []
        for L in lags:
            r, p, n = self._partial_correlation(frame, inp, sym, L)
            if not np.isnan(r):
                per_lag.append((L, r, p, n))
        if not per_lag:
            return None

        # Strongest lag by |partial r|.
        best_lag, best_r, best_p, n = max(per_lag, key=lambda t: abs(t[1]))

        # Within-pair correction for the lag search. Adjacent lags of a bursty
        # food are correlated, so the effective number of independent tests is
        # less than len(lags); estimate it and apply a Sidak adjustment on the
        # effective number of independent lags. The pair-level p that results
        # is the correct unit for the across-pair FDR step that follows.

        # Returns None if there isn't enough overlapping data.

        m_eff = self._effective_tests(frame, inp, lags)
        pair_p = 1.0 - (1.0 - best_p) ** m_eff
        pair_p = float(min(pair_p, 1.0))

        # Descriptive distributed-lag profile (signed partial r at each lag).
        lag_profile = {int(L): float(r) for L, r, _, _ in per_lag}

        return LaggedRelationship(
            input_name=inp,
            symptom_name=sym,
            best_lag_days=int(best_lag),
            effect_size=float(best_r),
            direction="aggravates" if best_r > 0 else "relieves",
            p_value=pair_p,
            q_value=1.0,  # filled in by FDR step
            n_observations=int(n),
            distributed_lag_profile=lag_profile,
        )

    def _effective_tests(self, frame: pd.DataFrame, inp: str, lags: list[int]) -> float:
        cols = {f"{inp}_lag{L}": frame[inp].shift(L) for L in lags}
        M = pd.DataFrame(cols).dropna()
        m = len(lags)
        if len(M) < m + 2:
            return float(m)
        try:
            corr = np.corrcoef(M.values, rowvar=False)
            eig = np.linalg.eigvalsh(corr)
            eig = np.clip(eig, 0, None)
            var_eig = np.var(eig, ddof=1)
            m_eff = 1 + (m - 1) * (1 - var_eig / m)
            return float(np.clip(m_eff, 1.0, m))
        except Exception:
            return float(m)

    @staticmethod
    def _rss(design: np.ndarray, y: np.ndarray) -> float:
        beta, *_ = np.linalg.lstsq(design, y, rcond=None)
        resid = y - design @ beta
        return float(resid @ resid)

    def _partial_correlation(self, frame, inp, sym, lag):
        C = self._build_confounders(frame, sym)
        x = frame[inp].shift(lag)
        y = frame[sym]
        data = pd.concat([x.rename("x"), y.rename("y"), C], axis=1).dropna()
        n = len(data)
        if n < self.cfg.min_paired_observations:
            return np.nan, np.nan, n

        ctrl = data.drop(columns=["x", "y"]).values
        if ctrl.shape[1] == 0:
            r, p = stats.pearsonr(data["x"], data["y"])
            return r, p, n

        # Residualize x and y against controls, then correlate residuals.
        ctrl_design = np.column_stack([np.ones(n), ctrl])
        bx, *_ = np.linalg.lstsq(ctrl_design, data["x"].values, rcond=None)
        by, *_ = np.linalg.lstsq(ctrl_design, data["y"].values, rcond=None)
        rx = data["x"].values - ctrl_design @ bx
        ry = data["y"].values - ctrl_design @ by
        if np.std(rx) < 1e-9 or np.std(ry) < 1e-9:
            return np.nan, np.nan, n
        r, p = stats.pearsonr(rx, ry)
        # Adjust p for the dof spent on controls.
        return r, p, n

    def _apply_fdr(self, candidates: list[LaggedRelationship]):
        pvals = np.array([c.p_value for c in candidates])
        order = np.argsort(pvals)
        m = len(pvals)
        q = np.empty(m)
        prev = 1.0
        # Step-up from largest p to smallest.
        for rank in range(m - 1, -1, -1):
            idx = order[rank]
            val = pvals[idx] * m / (rank + 1)
            prev = min(prev, val)
            q[idx] = min(prev, 1.0)
        for c, qv in zip(candidates, q):
            c.q_value = float(qv)
        return candidates

    def _lagged_pairs(self, frame, inp, sym, lag):
        x = frame[inp].shift(lag)
        y = frame[sym]
        d = pd.concat([x.rename("x"), y.rename("y")], axis=1).dropna()
        return d["x"].values, d["y"].values

    def _validate_out_of_sample(self, test_df, rel: LaggedRelationship):
        x, y = self._lagged_pairs(test_df, rel.input_name, rel.symptom_name,
                                  rel.best_lag_days)
        if len(x) < 6:
            rel.validated = None
            rel.validation_detail = "Insufficient holdout data to validate."
            return
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            r, p = stats.spearmanr(x, y)
        # The direction for 'aggravates' means a positive correlation.
        # So r > 0 should correspond to 'aggravates'.
        same_sign = (r > 0) == (rel.direction == "aggravates")
        rel.validated = bool(same_sign and p < 0.20)
        rel.validation_detail = (
            f"Holdout: r={r:+.2f}, p={p:.2f}, n={len(x)} "
            f"({'reproduced' if rel.validated else 'did not reproduce'})."
        )

import json
import os

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # headless
import matplotlib.pyplot as plt

import os

HERE = os.getcwd()
FIG = os.path.join(HERE, "figures")
OUT = os.path.join(HERE, "outputs")

# Create output directories if they don't exist
os.makedirs(FIG, exist_ok=True)
os.makedirs(OUT, exist_ok=True)

BG = "#0D0F0E"; CARD = "#1A1F1D"; ACCENT = "#A8C686"; WARN = "#E8A838"
DANGER = "#D96B6B"; TEXT = "#E8EDE9"; MID = "#9CA89E"; GOLD = "#D4A843"
plt.rcParams.update({
    "figure.facecolor": BG, "axes.facecolor": CARD, "savefig.facecolor": BG,
    "text.color": TEXT, "axes.labelcolor": TEXT, "xtick.color": MID,
    "ytick.color": MID, "axes.edgecolor": "#2A302D", "grid.color": "#2A302D",
    "font.family": "DejaVu Sans", "axes.titlecolor": TEXT, "font.size": 10,
})

def planted_set():
    return {(i, s) for i, s, *_ in GROUND_TRUTH}

def fig_signal_recovery():
    rows = generate_user(n_days=300, seed=3)
    eng = PersonalCorrelationEngine(EngineConfig())
    signals = eng.discover(rows, input_columns(), SYMPTOMS)

    planted = planted_set()
    # save signals + audit trail
    pd.DataFrame([{
        "input": s.input_name, "symptom": s.symptom_name, "direction": s.direction,
        "lag_days": s.best_lag_days, "effect_r": round(s.effect_size, 3),
        "confidence": round(1 - s.q_value, 3), "n": s.n_observations,
        "is_true_effect": (s.input_name, s.symptom_name) in planted,
    } for s in signals]).to_csv(os.path.join(OUT, "signals_single_user.csv"), index=False)

    pd.DataFrame([{
        "input": c.input_name, "symptom": c.symptom_name, "best_lag": c.best_lag_days,
        "effect_r": round(c.effect_size, 3), "p_value": round(c.p_value, 4),
        "q_value": round(c.q_value, 4), "n": c.n_observations,
        "is_planted": (c.input_name, c.symptom_name) in planted,
    } for c in eng.audit_trail]).to_csv(os.path.join(OUT, "audit_trail.csv"), index=False)

    # plot: planted truth (bars) vs recovered (markers)
    fig, ax = plt.subplots(figsize=(9, 5))
    labels = [f"{i}\u2192{s}" for i, s, *_ in GROUND_TRUTH]
    truth_strengths = [sign * strength for _, _, sign, _, strength in GROUND_TRUTH]
    xs = np.arange(len(labels))
    ax.bar(xs, truth_strengths, color="#2A302D", width=0.6, label="Planted effect (relative strength)")

    found = {(s.input_name, s.symptom_name): s for s in signals}
    for k, (i, s, sign, lag, strength) in enumerate(GROUND_TRUTH):
        rel = found.get((i, s))
        if rel:
            ax.scatter([k], [rel.effect_size * 3], color=ACCENT, s=140, zorder=5,
                       edgecolors="white", linewidths=1.2)
            ax.annotate(f"found\nlag {rel.best_lag_days}d", (k, rel.effect_size * 3),
                        textcoords="offset points", xytext=(0, 12), ha="center",
                        color=ACCENT, fontsize=8, fontweight="bold")
        else:
            ax.scatter([k], [0], marker="x", color=DANGER, s=80, zorder=5)
            ax.annotate("missed", (k, 0), textcoords="offset points", xytext=(0, 12),
                        ha="center", color=DANGER, fontsize=8)

    # decoys recovered (should be none) — flag any false positives
    fps = [s for s in signals if (s.input_name, s.symptom_name) not in planted]
    ax.axhline(0, color="#2A302D", lw=1)
    ax.set_ylim(-1.6, 2.0)
    ax.set_xticks(xs); ax.set_xticklabels(labels, fontsize=9)
    ax.set_ylabel("Effect direction & relative magnitude")
    ax.set_title(f"Signal Recovery — 1 user, 300 days\n"
                 f"{len(signals)} promoted from {len(eng.audit_trail)} pairs · "
                 f"{len(fps)} false positives", fontsize=12)
    ax.legend(loc="lower right", facecolor=CARD, edgecolor="#2A302D", labelcolor=TEXT)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "1_signal_recovery.png"), dpi=130)
    plt.close(fig)
    return signals, eng

def fig_power_curve():
    planted = planted_set()
    days_grid = [90, 150, 250, 400, 600]
    n_users = 8
    rows_out = []
    for days in days_grid:
        tp = fp = 0
        for seed in range(n_users):
            rows = generate_user(n_days=days, seed=seed)
            sig = PersonalCorrelationEngine(EngineConfig()).discover(rows, input_columns(), SYMPTOMS)
            for s in sig:
                if (s.input_name, s.symptom_name) in planted:
                    tp += 1
                else:
                    fp += 1
        avg_tp = tp / n_users
        avg_fp = fp / n_users
        precision = tp / (tp + fp) if (tp + fp) else float("nan")
        rows_out.append({"days": days, "avg_true_found": round(avg_tp, 2),
                         "avg_false_pos": round(avg_fp, 2),
                         "precision": round(precision, 3) if not np.isnan(precision) else None,
                         "max_true": len(GROUND_TRUTH)})
    df = pd.DataFrame(rows_out)
    df.to_csv(os.path.join(OUT, "power_curve.csv"), index=False)

    fig, ax1 = plt.subplots(figsize=(9, 5))
    ax1.plot(df["days"], df["avg_true_found"], "-o", color=ACCENT, lw=2.5,
             label=f"True effects found (of {len(GROUND_TRUTH)})")
    ax1.plot(df["days"], df["avg_false_pos"], "-o", color=DANGER, lw=2,
             label="False positives")
    ax1.set_xlabel("Days of logging"); ax1.set_ylabel("Avg. count per user")
    ax1.set_ylim(-0.2, len(GROUND_TRUTH) + 0.3)

    ax2 = ax1.twinx()
    ax2.plot(df["days"], df["precision"] * 100, "--", color=GOLD, lw=1.8, label="Precision (%)")
    ax2.set_ylabel("Precision (%)", color=GOLD); ax2.set_ylim(0, 105)
    ax2.tick_params(axis="y", colors=GOLD)

    ax1.set_title("Power Curve — recovery & precision vs. logging duration\n"
                  "(avg of 8 simulated responders; 4 true effects + 8 decoys)", fontsize=12)
    l1, lab1 = ax1.get_legend_handles_labels()
    l2, lab2 = ax2.get_legend_handles_labels()
    ax1.legend(l1 + l2, lab1 + lab2, loc="center right", facecolor=CARD,
               edgecolor="#2A302D", labelcolor=TEXT)
    ax1.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "2_power_curve.png"), dpi=130)
    plt.close(fig)
    return df

def fig_lag_recovery():
    planted = {(i, s): lag for i, s, _, lag, _ in GROUND_TRUTH}
    true_lags, found_lags, names = [], [], []
    for seed in range(12):
        rows = generate_user(n_days=400, seed=seed)
        eng = PersonalCorrelationEngine(EngineConfig())
        eng.discover(rows, input_columns(), SYMPTOMS)
        for c in eng.audit_trail:
            key = (c.input_name, c.symptom_name)
            if key in planted:
                true_lags.append(planted[key] + np.random.uniform(-0.12, 0.12))
                found_lags.append(c.best_lag_days)
                names.append(f"{c.input_name}\u2192{c.symptom_name}")

    fig, ax = plt.subplots(figsize=(8, 6))
    palette = {n: c for n, c in zip(sorted(set(names)), [ACCENT, WARN, GOLD, "#6BA3D9"])}
    for n in sorted(set(names)):
        xs = [t for t, nm in zip(true_lags, names) if nm == n]
        ys = [f for f, nm in zip(found_lags, names) if nm == n]
        ax.scatter(xs, ys, color=palette[n], s=60, alpha=0.7, edgecolors="none", label=n)
    lim = [-0.5, 5.5]
    ax.plot(lim, lim, "--", color=MID, lw=1, label="perfect recovery")
    ax.set_xlim(lim); ax.set_ylim(lim)
    ax.set_xlabel("True planted lag (days)"); ax.set_ylabel("Lag the engine found (days)")
    ax.set_title("Lag Recovery — does the engine find the RIGHT delay?\n"
                 "(12 users × 4 planted effects, 400 days each)", fontsize=12)
    ax.legend(facecolor=CARD, edgecolor="#2A302D", labelcolor=TEXT, fontsize=8)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "3_lag_recovery.png"), dpi=130)
    plt.close(fig)

def fig_fdr_funnel(eng):
    cfg = eng.cfg
    n_tested = len(eng.audit_trail)
    after_fdr = sum(1 for c in eng.audit_trail if c.q_value <= cfg.fdr_alpha)
    after_effect = sum(1 for c in eng.audit_trail
                       if c.q_value <= cfg.fdr_alpha and abs(c.effect_size) >= cfg.min_effect_size)
    # validated = promoted signals (re-run discover for a clean count)
    promoted = len(eng.discover(generate_user(n_days=300, seed=3),
                                input_columns(), SYMPTOMS))

    stages = ["Pairs\ntested", "Survive\nFDR", "Pass effect\nfloor", "Validated\n(promoted)"]
    counts = [n_tested, after_fdr, after_effect, promoted]
    colors = ["#2A302D", "#4A5A45", WARN, ACCENT]

    fig, ax = plt.subplots(figsize=(9, 5))
    bars = ax.bar(stages, counts, color=colors, width=0.62)
    for b, c in zip(bars, counts):
        ax.annotate(str(c), (b.get_x() + b.get_width() / 2, b.get_height()),
                    textcoords="offset points", xytext=(0, 5), ha="center",
                    color=TEXT, fontweight="bold")
    ax.set_ylabel("Number of candidate relationships")
    ax.set_title("The Skepticism Funnel — how many 'findings' survive each filter\n"
                 "(this is what separates a real model from p-hacking)", fontsize=12)
    ax.grid(alpha=0.2, axis="y")
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "4_fdr_funnel.png"), dpi=130)
    plt.close(fig)
    return {"tested": n_tested, "after_fdr": after_fdr,
            "after_effect_floor": after_effect, "promoted": promoted}

def fig_hypothesis_loop():
    # Train on growing data, generate a hypothesis, grade it on the following week.
    weeks = list(range(6, 26, 2))
    correct = []
    for w in weeks:
        hits = total = 0
        for seed in range(10):
            train = generate_user(n_days=w * 7, seed=seed)
            eng = PersonalCorrelationEngine(EngineConfig())
            sig = eng.discover(train, input_columns(), SYMPTOMS)
            h = eng.generate_hypothesis(sig)
            if not h:
                continue
            nextwk = generate_user(n_days=10, seed=1000 + seed)
            res = eng.evaluate_hypothesis(h, nextwk)
            total += 1
            hits += 1 if res.confirmed else 0
        correct.append(hits / total if total else np.nan)

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(weeks, np.array(correct) * 100, "-o", color=GOLD, lw=2.5)
    ax.axhline(50, color=MID, ls="--", lw=1, label="chance (50%)")
    ax.set_xlabel("Weeks of data before committing the hypothesis")
    ax.set_ylabel("Next-week hypothesis confirmed (%)")
    ax.set_ylim(0, 105)
    ax.set_title("Predict \u2192 Commit \u2192 Grade — the n-of-1 loop\n"
                 "honest forward test: a prediction made, then checked on fresh data", fontsize=12)
    ax.legend(facecolor=CARD, edgecolor="#2A302D", labelcolor=TEXT)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG, "5_hypothesis_loop.png"), dpi=130)
    plt.close(fig)
    return dict(zip([f"week_{w}" for w in weeks],
                    [round(c, 3) if not np.isnan(c) else None for c in correct]))

def main():
    print("Augur PoC — running on artificial data...\n")

    print("[1/5] Single-user signal recovery + audit trail")
    signals, eng = fig_signal_recovery()
    print(f"      promoted {len(signals)} signals; saved signals_single_user.csv, audit_trail.csv")

    print("[2/5] Power curve")
    pc = fig_power_curve()
    print("      saved power_curve.csv")

    print("[3/5] Lag recovery accuracy")
    fig_lag_recovery()

    print("[4/5] FDR skepticism funnel")
    funnel = fig_fdr_funnel(eng)

    print("[5/5] Hypothesis loop accuracy")
    loop = fig_hypothesis_loop()

    # ── Population bootstrapping: fit, present findings, SAVE the prior ────
    print("\n[bootstrap 1/3] Fitting population prior from 60 mature users...")
    prior = fit_population(n_users=60, n_days=300)
    print(f"                learned {len(prior.priors)} population relationships:")
    for p in prior.summary():
        print(f"                  {p.key[0]:>10} -> {p.key[1]:<12} "
              f"mu={p.mu:+.3f} tau={p.tau:.3f} prevalence={p.prevalence:.0%} (n={p.n_users})")

    print("[bootstrap 2/3] Saving fitted prior to outputs/population_prior.json ...")
    prior.save(os.path.join(OUT, "population_prior.json"))

    print("[bootstrap 3/3] Evaluating new-user head start + figure...")
    pool = evaluate_pooling(prior, [7, 14, 30, 60, 120, 200], n_new_users=40)
    fig_pooling_headstart(pool)
    for i, d in enumerate(pool["days"]):
        ea, pl = pool["engine_alone_mae"][i], pool["pooled_mae"][i]
        lift = (ea - pl) / ea * 100 if ea else 0
        print(f"                {d:>3}d: engine MAE={ea:.3f}  pooled MAE={pl:.3f}  "
              f"-> {lift:+.0f}% error reduction  (engine answered {pool['engine_coverage'][i]:.0%})")
    i14 = pool["days"].index(14)
    headline = (f"At 14 days, pooling cuts new-user estimation error by "
                f"{(pool['engine_alone_mae'][i14]-pool['pooled_mae'][i14])/pool['engine_alone_mae'][i14]*100:.0f}% "
                f"vs. the engine alone.")
    print(f"\n      HEADLINE: {headline}")

    summary = {
        "single_user": {
            "promoted_signals": [s.human_summary() for s in signals],
            "n_pairs_tested": len(eng.audit_trail),
        },
        "power_curve": pc.to_dict(orient="records"),
        "fdr_funnel": funnel,
        "hypothesis_loop_confirm_rate": loop,
        "population_priors": [
            {"input": p.key[0], "symptom": p.key[1], "lag": p.lag,
             "mu": p.mu, "tau": p.tau, "prevalence": p.prevalence, "n_users": p.n_users}
            for p in prior.summary()
        ],
        "pooling_evaluation": pool,
        "pooling_headline": headline,
        "ground_truth": truth_table().to_dict(orient="records"),
        "config": {
            "min_lag_days": eng.cfg.min_lag_days, "max_lag_days": eng.cfg.max_lag_days,
            "min_paired_observations": eng.cfg.min_paired_observations,
            "min_effect_size": eng.cfg.min_effect_size, "fdr_alpha": eng.cfg.fdr_alpha,
            "holdout_fraction": eng.cfg.holdout_fraction,
        },
    }
    with open(os.path.join(OUT, "poc_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    print("\nDone. Figures in figures/, data in outputs/, summary in outputs/poc_summary.json")


# (pooling section is defined below; the single __main__ guard lives at the very
#  end of the file so every function exists before main() runs)


def generate_cohort(n_users: int, n_days: int, pop_seed: int = 42):
  return [generate_cohort_user(u, n_days, pop_seed) for u in range(n_users)]

def generate_cohort_user(user_id: int, n_days: int, pop_seed: int) -> tuple[pd.DataFrame, dict]:
    global GROUND_TRUTH # Reference the global GROUND_TRUTH

    # Each user gets a reproducible random stream based on a hash of their ID
    # and the population seed, so that changes to pop_seed affect everyone,
    # but individual users can be regenerated.
    rng = np.random.default_rng(abs(hash(f"{user_id}-{pop_seed}")) % (2**32 - 1))

    personal_ground_truth = []
    true_strengths = {}
    for inp, sym, sign, lag, pop_strength in GROUND_TRUTH:
        # lognormal-ish positive multiplier centered on 1.0, occasionally ~0
        mult = max(0.0, rng.normal(1.0, 0.45))
        if rng.random() < 0.15:
            mult *= rng.uniform(0.0, 0.2)  # non-responder for this pathway
        personal_ground_truth.append((inp, sym, sign, lag, pop_strength * mult))
        true_strengths[(inp, sym)] = sign * pop_strength * mult

    original_ground_truth = GROUND_TRUTH # Save the original global GROUND_TRUTH
    GROUND_TRUTH = personal_ground_truth # Temporarily set to personalized version
    try:
        df = generate_user(n_days=n_days, seed=int(rng.integers(1, 10**6))) # Use global generate_user
    finally:
        GROUND_TRUTH = original_ground_truth # Restore the original global GROUND_TRUTH
    return df, true_strengths

@dataclass
class PriorEstimate:
    key: tuple
    lag: int
    mu: float
    tau: float
    n_users: int
    prevalence: float

class PopulationPrior:
    def __init__(self):
      self.priors: dict[tuple, PriorEstimate] = {}

    def fit(self, per_user_estimates: dict[tuple, list[tuple]]):
        for key, rows in per_user_estimates.items():
            rs = np.array([r for r, _, _ in rows], dtype=float)
            ses = np.array([se for _, se, _ in rows], dtype=float)
            lags = [lag for _, _, lag in rows]
            if len(rs) < 3:
                continue  # too few users to call it a population effect
            mu = float(np.average(rs, weights=1.0 / np.maximum(ses**2, 1e-6)))
            # total variance of estimates = between-person (tau^2) + within (se^2)
            total_var = float(np.var(rs, ddof=1))
            mean_within = float(np.mean(ses**2))
            tau2 = max(0.0, total_var - mean_within)   # method-of-moments tau^2
            # prevalence: fraction whose own estimate is a non-trivial effect
            prevalence = float(np.mean(np.abs(rs) >= 0.15))
            lag_mode = max(set(lags), key=lags.count)

            self.priors[key] = PriorEstimate(
                key=key, lag=lag_mode, mu=mu, tau=math.sqrt(tau2),
                n_users=len(rs), prevalence=prevalence,
            )
    def predict(self, key, user_r=None, user_se=None):
        prior = self.priors.get(key)
        if prior is None:
            # nothing pooled for this pair; fall back to the user's own or zero
            return {"estimate": user_r if user_r is not None else 0.0,
                    "weight_personal": 1.0 if user_r is not None else 0.0,
                    "source": "personal_only", "lag": None}

        if user_r is None or user_se is None:
            return {"estimate": prior.mu, "weight_personal": 0.0,
                    "source": "population_prior", "lag": prior.lag,
                    "mu": prior.mu, "tau": prior.tau, "n_users": prior.n_users}

        tau2 = prior.tau**2
        w = tau2 / (tau2 + user_se**2 + 1e-9)        # reliability weight
        est = w * user_r + (1 - w) * prior.mu
        return {"estimate": float(est), "weight_personal": float(w),
                "source": "blended", "lag": prior.lag,
                "mu": prior.mu, "tau": prior.tau, "n_users": prior.n_users}

    def summary(self):
        return sorted(self.priors.values(), key=lambda p: -abs(p.mu))

    # ── persistence: this is the closest thing this model has to "weights" ────
    def save(self, path):
        """Save the fitted prior (the learned population parameters) to JSON."""
        payload = {
            "model": "PopulationPrior (empirical-Bayes shrinkage)",
            "n_relationships": len(self.priors),
            "priors": [
                {"input": p.key[0], "symptom": p.key[1], "lag": p.lag,
                 "mu": p.mu, "tau": p.tau, "n_users": p.n_users,
                 "prevalence": p.prevalence}
                for p in self.summary()
            ],
        }
        with open(path, "w") as f:
            json.dump(payload, f, indent=2)
        return path

    @classmethod
    def load(cls, path):
        """Reload a saved prior so a deployed app gives new users a head start."""
        with open(path) as f:
            payload = json.load(f)
        obj = cls()
        for r in payload["priors"]:
            key = (r["input"], r["symptom"])
            obj.priors[key] = PriorEstimate(
                key=key, lag=r["lag"], mu=r["mu"], tau=r["tau"],
                n_users=r["n_users"], prevalence=r["prevalence"],
            )
        return obj


CANDIDATE_PAIRS = [(i, s) for i, s, *_ in GROUND_TRUTH]


def estimate_pair(engine, df, inp, sym):
    """Raw (r, se, lag) for one (input, symptom) pair from one user's data."""
    frame = engine._prepare_frame(df)
    best = None
    for lag in range(engine.cfg.min_lag_days, engine.cfg.max_lag_days + 1):
        r, p, n = engine._partial_correlation(frame, inp, sym, lag)
        if np.isnan(r):
            continue
        if best is None or abs(r) > abs(best[0]):
            best = (r, lag, n)
    if best is None:
        return None
    r, lag, n = best
    if n < 5:
        return None
    se = math.sqrt(max(1e-6, (1 - r ** 2) / max(1, n - 2)))
    return (float(r), float(se), int(lag))


def fit_population(n_users=60, n_days=300, pop_seed=42):
    """Fit the population prior from many mature users' per-user estimates."""
    eng = PersonalCorrelationEngine(EngineConfig())
    per_pair = {pair: [] for pair in CANDIDATE_PAIRS}
    for u in range(n_users):
        df, _ = generate_cohort_user(u, n_days, pop_seed)
        for (inp, sym) in CANDIDATE_PAIRS:
            est = estimate_pair(eng, df, inp, sym)
            if est:
                per_pair[(inp, sym)].append(est)
    prior = PopulationPrior()
    prior.fit(per_pair)
    return prior


def _norm(signed_strength):
    """Squash a planted strength onto the correlation scale we compare on."""
    return float(np.tanh(signed_strength))


def evaluate_pooling(prior, days_grid, n_new_users=40, pop_seed=99):
    """New-user estimation error: engine-alone vs. pooled, vs. each user's truth."""
    eng = PersonalCorrelationEngine(EngineConfig())
    res = {"days": [], "engine_alone_mae": [], "pooled_mae": [], "engine_coverage": []}
    for days in days_grid:
        err_engine, err_pooled, covered = [], [], []
        for u in range(n_new_users):
            df, truth = generate_cohort_user(u, days, pop_seed)
            for pair in CANDIDATE_PAIRS:
                true_eff = _norm(truth[pair])
                est = estimate_pair(eng, df, pair[0], pair[1])
                if est:
                    r_i, se_i, _ = est
                    err_engine.append(abs(r_i - true_eff)); covered.append(1)
                    blend = prior.predict(pair, user_r=r_i, user_se=se_i)
                else:
                    err_engine.append(abs(0.0 - true_eff)); covered.append(0)
                    blend = prior.predict(pair, user_r=None, user_se=None)
                err_pooled.append(abs(blend["estimate"] - true_eff))
        res["days"].append(days)
        res["engine_alone_mae"].append(round(float(np.mean(err_engine)), 4))
        res["pooled_mae"].append(round(float(np.mean(err_pooled)), 4))
        res["engine_coverage"].append(round(float(np.mean(covered)), 3))
    return res


def fig_pooling_headstart(results):
    fig, ax = plt.subplots(figsize=(9, 5))
    d = results["days"]
    ax.plot(d, results["engine_alone_mae"], "-o", color=DANGER, lw=2.5,
            label="Engine alone (status quo)")
    ax.plot(d, results["pooled_mae"], "-o", color=ACCENT, lw=2.5,
            label="With population pooling (prototype)")
    ax.set_xlabel("Days of data the new user has logged")
    ax.set_ylabel("Mean abs. error vs. the user's TRUE effect")
    ax.set_title("Population pooling gives new users a head start\n"
                 "lower error = better personal estimate from less data", fontsize=12)
    ax.legend(facecolor=CARD, edgecolor="#2A302D", labelcolor=TEXT)
    ax.grid(alpha=0.25)
    ax.annotate("biggest win\nwhen data is scarce",
                (d[0], results["engine_alone_mae"][0]),
                textcoords="offset points", xytext=(40, -10), color=GOLD, fontsize=9,
                arrowprops=dict(arrowstyle="->", color=GOLD))
    fig.tight_layout(); fig.savefig(os.path.join(FIG, "6_pooling_headstart.png"), dpi=130)
    plt.close(fig)

if __name__ == "__main__":
    main()

    # Display the generated graphs inline when running in Colab/Jupyter.
    # Outside a notebook there is no IPython, so this is optional ─ the figures
    # are already saved in the figures/ folder regardless.
    try:
        from IPython.display import Image, display
        print("\n--- Generated Graphs ---")
        for filename in sorted(os.listdir(FIG)):
            if filename.endswith(".png"):
                print(f"\nDisplaying: {filename}")
                display(Image(filename=os.path.join(FIG, filename)))
    except ModuleNotFoundError:
        print("\n(Not in a notebook ─ figures saved to the figures/ folder.)")

import pandas as pd
import os

audit_trail_df = pd.read_csv(os.path.join(OUT, "audit_trail.csv"))
signals_df = pd.read_csv(os.path.join(OUT, "signals_single_user.csv"))

# Identify planted effects
planted_effects_audit = audit_trail_df[audit_trail_df['is_planted'] == True].copy()

# Identify promoted signals (from the planted effects that were successfully discovered)
# We can use the original planted_set for a robust check
planted_set_keys = set()
for i, s, _, _, _ in GROUND_TRUTH:
    planted_set_keys.add((i, s))

# Find which planted effects are in the signals_df
promoted_planted_keys = set(signals_df[signals_df['is_true_effect'] == True].apply(lambda row: (row['input'], row['symptom']), axis=1))

# Find the planted effect that was NOT promoted
unpromoted_planted_keys = planted_set_keys - promoted_planted_keys

if unpromoted_planted_keys:
    print(f"The following planted effect(s) were NOT promoted: {unpromoted_planted_keys}")
    # Get details for the unpromoted planted effect from the audit trail
    for input_name, symptom_name in unpromoted_planted_keys:
        unpromoted_detail = planted_effects_audit[
            (planted_effects_audit['input'] == input_name) &
            (planted_effects_audit['symptom'] == symptom_name)
        ]
        if not unpromoted_detail.empty:
            print("Details from audit_trail for the unpromoted effect:")
            display(unpromoted_detail)
        else:
            print(f"No audit trail entry found for {input_name}-{symptom_name}")
else:
    print("All planted effects were promoted.")

# Also display the overall configuration values used by the engine for context
print("\nEngine Configuration (relevant to filtering):")
eng = PersonalCorrelationEngine(EngineConfig())
print(f"  FDR Alpha (fdr_alpha): {eng.cfg.fdr_alpha}")
print(f"  Minimum Effect Size (min_effect_size): {eng.cfg.min_effect_size}")

audit_trail_df = pd.read_csv(os.path.join(OUT, "audit_trail.csv"))

# Prepare GROUND_TRUTH for comparison
true_effects_list = []
for inp, sym, sign, lag, strength in GROUND_TRUTH:
    true_effects_list.append({
        'input': inp,
        'symptom': sym,
        'true_sign': sign,
        'true_lag': lag,
        'true_strength': strength
    })
true_effects_df = pd.DataFrame(true_effects_list)

# Filter audit_trail for planted effects and merge with true_effects_df
planted_comparison_df = audit_trail_df[audit_trail_df['is_planted'] == True][['input', 'symptom', 'best_lag', 'effect_r', 'q_value']]
comparison_df = pd.merge(planted_comparison_df, true_effects_df, on=['input', 'symptom'], how='left')

# Adjust engine's effect_r for comparison if needed (e.g., if true_strength is an absolute value)
# For now, we'll assume true_strength represents the magnitude and sign * strength is the actual value
comparison_df['true_effect_value'] = comparison_df['true_sign'] * comparison_df['true_strength']

print("Comparison of Planted Effects: True Strength vs. Engine's effect_r")
display(comparison_df[['input', 'symptom', 'true_effect_value', 'effect_r', 'true_lag', 'best_lag', 'q_value']])

def generate_cohort(n_users: int, n_days: int, pop_seed: int = 42):
  return [generate_cohort_user(u, n_days, pop_seed) for u in range(n_users)]

def generate_cohort_user(user_id: int, n_days: int, pop_seed: int) -> tuple[pd.DataFrame, dict]:
    global GROUND_TRUTH # Reference the global GROUND_TRUTH

    # Each user gets a reproducible random stream based on a hash of their ID
    # and the population seed, so that changes to pop_seed affect everyone,
    # but individual users can be regenerated.
    rng = np.random.default_rng(abs(hash(f"{user_id}-{pop_seed}")) % (2**32 - 1))

    personal_ground_truth = []
    true_strengths = {}
    for inp, sym, sign, lag, pop_strength in GROUND_TRUTH:
        # lognormal-ish positive multiplier centered on 1.0, occasionally ~0
        mult = max(0.0, rng.normal(1.0, 0.45))
        if rng.random() < 0.15:
            mult *= rng.uniform(0.0, 0.2)  # non-responder for this pathway
        personal_ground_truth.append((inp, sym, sign, lag, pop_strength * mult))
        true_strengths[(inp, sym)] = sign * pop_strength * mult

    original_ground_truth = GROUND_TRUTH # Save the original global GROUND_TRUTH
    GROUND_TRUTH = personal_ground_truth # Temporarily set to personalized version
    try:
        df = generate_user(n_days=n_days, seed=int(rng.integers(1, 10**6))) # Use global generate_user
    finally:
        GROUND_TRUTH = original_ground_truth # Restore the original global GROUND_TRUTH
    return df, true_strengths

@dataclass
class PriorEstimate:
    key: tuple
    lag: int
    mu: float
    tau: float
    n_users: int
    prevalence: float

class PopulationPrior:
    def __init__(self):
      self.priors: dict[tuple, PriorEstimate] = {}

    def fit(self, per_user_estimates: dict[tuple, list[tuple]]):
        for key, rows in per_user_estimates.items():
            rs = np.array([r for r, _, _ in rows], dtype=float)
            ses = np.array([se for _, se, _ in rows], dtype=float)
            lags = [lag for _, _, lag in rows]
            if len(rs) < 3:
                continue  # too few users to call it a population effect
            mu = float(np.average(rs, weights=1.0 / np.maximum(ses**2, 1e-6)))
            # total variance of estimates = between-person (tau^2) + within (se^2)
            total_var = float(np.var(rs, ddof=1))
            mean_within = float(np.mean(ses**2))
            tau2 = max(0.0, total_var - mean_within)   # method-of-moments tau^2
            # prevalence: fraction whose own estimate is a non-trivial effect
            prevalence = float(np.mean(np.abs(rs) >= 0.15))
            lag_mode = max(set(lags), key=lags.count)

            self.priors[key] = PriorEstimate(
                key=key, lag=lag_mode, mu=mu, tau=math.sqrt(tau2),
                n_users=len(rs), prevalence=prevalence,
            )
    def predict(self, key, user_r=None, user_se=None):
        prior = self.priors.get(key)
        if prior is None:
            # nothing pooled for this pair; fall back to the user's own or zero
            return {"estimate": user_r if user_r is not None else 0.0,
                    "weight_personal": 1.0 if user_r is not None else 0.0,
                    "source": "personal_only", "lag": None}

        if user_r is None or user_se is None:
            return {"estimate": prior.mu, "weight_personal": 0.0,
                    "source": "population_prior", "lag": prior.lag,
                    "mu": prior.mu, "tau": prior.tau, "n_users": prior.n_users}

        tau2 = prior.tau**2
        w = tau2 / (tau2 + user_se**2 + 1e-9)        # reliability weight
        est = w * user_r + (1 - w) * prior.mu
        return {"estimate": float(est), "weight_personal": float(w),
                "source": "blended", "lag": prior.lag,
                "mu": prior.mu, "tau": prior.tau, "n_users": prior.n_users}

    def summary(self):
        return sorted(self.priors.values(), key=lambda p: -abs(p.mu))